import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

abstract class Fuzzer {

    /**
     * Simply read the FIRST line of the result returned by the exec file.
     * @param inputFile the input file we give to the exec file.
     * @return the FIRST line of the result generated by the exec file.
     */
    protected static String run_process(Path inputFile) {
        try {
            String line;
            Process p = Runtime.getRuntime().exec("./converter_static " + inputFile + " testoutput.img");
            BufferedReader bre = new BufferedReader(new InputStreamReader(p.getErrorStream()));
            if ((line = bre.readLine()) != null) {
                return line;
            }
            bre.close();
            p.waitFor();
        }
        catch (Exception err) {
            err.printStackTrace();
        }
        return null;
    }
    /**
     * Read a file.
     * @param file: the file to read on.
     * @return a byte array from the file.
     */
    protected static byte[] read_file(File file) {
        byte[] data = new byte[0];
        try {
            data = Files.readAllBytes(file.toPath());
        } catch (IOException e) {
            e.printStackTrace();
        }
        return data;
    }

    /**
     * Printing the data given in argument for debugging purpose.
     * @param data the tab of byte.
     * @param numberTests the number of tests to do.
     * @param maxNumberModif the maximum number of modif to do.
     * @param percentChange the max percent of random changes.
     */
    private static void print_data(byte[] data, int numberTests, int maxNumberModif, double percentChange) {
        System.out.println("Printing all the data : ");
        System.out.println("NbrTests : " + numberTests);
        System.out.println("MaxNumberOfTests : " + maxNumberModif);
        System.out.println("percentChange : " + percentChange);
        System.out.println("File Data : ");
        for (int i = 0; i < data.length; i++) {
            System.out.println("Data at : " + i + " : ");
            System.out.println(data[i]);
        }
        System.out.println("The data translated : ");
        String str = new String(data, StandardCharsets.UTF_8);
        System.out.println(str);
        System.out.println("----- End -----");
    }
}
